apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: oracledb
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbTo1MDAwIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6ImFkbWluIiwiZW1haWwiOiJzYWxhbmlzQHJlZGhhdC5jb20iLCJhdXRoIjoiWVdSdGFXNDZZV1J0YVc0PSJ9fX0=
type: kubernetes.io/dockerconfigjson
