apiVersion: v1
kind: Service
metadata:
  name: oracle
  namespace: oracledb
spec:
  type: NodePort
  selector:
    app: oracledb-app
  ports:
  - name: listener
    port: 1521
    protocol: TCP
  - name: xmldb
    port: 5500
    protocol: TCP
